### ISSUE TITLE
[Question] When to use gcp-night-king

### ISSUE THREAD

**Issue by paprickar** [itamaro/gcp-night-king#4]
Hello,

I would like to understand better in which scenarios gcp-night-king can help.

From the description I understand that based on a Pub/Sub queue gcp-night-king will restart an Preemptible VM instances instance.

Preemptible VM can be terminated at any time by Google for that it is a lot cheaper.
To my knowledge there is no or only a very short notice period if a instance is getting terminated.
https://cloud.google.com/compute/docs/instances/preemptible#preemption_selection

How can gcp-night-king help here? or is gcp-night-king just general service where you can send a message into the queue and trigger a reboot on your own?

Best
Patrick

**Comment by itamaro** [comment]
Hey @paprickar thanks for the question!

originally, this was a small service I hacked together to auto-restart GCE VM's that got preempted as part of an unmanaged cluster.
it worked by leveraging the GCE shutdown script, as described in the [readme](https://github.com/itamaro/gcp-night-king#configure-shutdown-script) - the machine that is about to get preempted would send a pubsub message before it's terminated.
the shutdown script is also covered in [Google cloud docs](https://cloud.google.com/compute/docs/instances/preemptible#preemption_process).

I wouldn't recommend this as a general approach to get preemptible machines restarted. I believe Google cloud has better solutions built-in, when using managed clusters / node pools / whatever the terminology is today. It was useful for a specific use case we had at the time :-)

**Comment by paprickar** [comment]
Hey @itamaro thanks for the very fast response,

I currently indeed use GKE with preemptible nodes in managed node pools and they working great.
But under some circumstances two nodes get restarted at the same time and then some deployments might don`t have any active pod anymore.

That`s why I thought I can maybe restart nodes on my own to prevent this.

Anyway I will find a way - thanks again!
